import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getPlatformProxy } from "wrangler";
import { upsertPatronOverride, upsertSession } from "../../src/lib/db";
import { buildE2eFixtureSeed, readFounderPatronId } from "../../e2e/helpers/session";

const ROOT = resolve(import.meta.dirname, "..", "..");
const DEV_VARS_PATH = resolve(ROOT, ".dev.vars");
const ENGINE_MOCK_PATH = resolve(ROOT, "src/lib/engine-mock.generated.ts");

// Local-only values, generated per machine: this file is written only when the
// repository has no .dev.vars, and .dev.vars is gitignored. The signing and
// encryption keys are random so no valid session can be minted from repository
// contents alone.
function localDevVars(): string {
  return [
    "# Generated by scripts/e2e/setup-e2e-env.ts for local Playwright runs.",
    "# generated-by: scripts/e2e/setup-e2e-env.ts",
    `SESSION_SECRET=${randomBytes(32).toString("hex")}`,
    `TOKEN_ENCRYPTION_KEY=${randomBytes(32).toString("hex")}`,
    "CREATOR_ADMIN_PATREON_IDS=424242",
    "PATREON_CLIENT_ID=e2e-local-client-id",
    "PATREON_CLIENT_SECRET=e2e-local-client-secret",
    "PATREON_REDIRECT_URI=http://127.0.0.1:3100/api/auth/callback",
  ].join("\n");
}

function ensureDevVars(): void {
  if (existsSync(DEV_VARS_PATH)) {
    return;
  }
  writeFileSync(DEV_VARS_PATH, `${localDevVars()}\n`, "utf-8");
  console.log("[e2e] wrote a local .dev.vars with throwaway bindings");
}

function ensureEngineMock(): void {
  if (existsSync(ENGINE_MOCK_PATH)) {
    return;
  }
  execFileSync("npx", ["tsx", "scripts/generate-engine-mock.ts"], { cwd: ROOT, stdio: "inherit" });
}

function applyLocalMigrations(): void {
  execFileSync("npx", ["wrangler", "d1", "migrations", "apply", "DB", "--local"], {
    cwd: ROOT,
    stdio: "inherit",
  });
}

async function seedFixtures(): Promise<void> {
  const founderPatronId = readFounderPatronId();
  const seed = buildE2eFixtureSeed(founderPatronId);
  const proxy = await getPlatformProxy();
  const db = proxy.env.DB as D1Database;

  try {
    for (const session of seed.sessions) {
      await upsertSession(db, session);
    }
    for (const override of seed.overrides) {
      await upsertPatronOverride(db, override);
    }
    if (founderPatronId) {
      // Only reachable with the generated .dev.vars, so the founder id is a
      // disposable fixture: the suite must prove the env-bootstrap path rather
      // than read a pre-seeded grant.
      await db
        .prepare("DELETE FROM patron_overrides WHERE patron_id = ?")
        .bind(founderPatronId)
        .run();
    }
    console.log(`[e2e] seeded ${seed.sessions.length} session fixture(s)`);
  } finally {
    await proxy.dispose();
  }
}

async function main(): Promise<void> {
  ensureDevVars();
  ensureEngineMock();
  applyLocalMigrations();
  await seedFixtures();
  console.log("[e2e] local environment ready");
}

main().catch((error: unknown) => {
  console.error("[e2e] setup failed:", error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
