import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getPlatformProxy } from "wrangler";
import { upsertPatronOverride, upsertSession } from "../../src/lib/db";
import {
  buildE2eFixtureSeed,
  readFounderPatronId,
  FOUNDER_PATRON_ID_KEY,
  GENERATED_DEV_VARS_MARKER,
} from "../../e2e/helpers/session";
import { seededShellFixture } from "../../e2e/fixtures/engine-boot-profile";

const ROOT = resolve(import.meta.dirname, "..", "..");
const DEV_VARS_PATH = resolve(ROOT, ".dev.vars");
const ENGINE_MOCK_PATH = resolve(ROOT, "src/lib/engine-mock.generated.ts");

// Disposable founder identity. Both keys carry it and must agree: the worker reads
// CREATOR_ADMIN_PATREON_IDS from .dev.vars to bootstrap, and the suite deletes the
// override row for E2E_FOUNDER_PATRON_ID only, so no real creator id is ever touched.
const E2E_FOUNDER_PATREON_ID = "424242";

// Local-only values, generated per machine: this file is written only when the
// repository has no .dev.vars, and .dev.vars is gitignored. The signing and
// encryption keys are random so no valid session can be minted from repository
// contents alone.
function localDevVars(): string {
  return [
    "# Generated by scripts/e2e/setup-e2e-env.ts for local Playwright runs.",
    GENERATED_DEV_VARS_MARKER,
    `SESSION_SECRET=${randomBytes(32).toString("hex")}`,
    `TOKEN_ENCRYPTION_KEY=${randomBytes(32).toString("hex")}`,
    `CREATOR_ADMIN_PATREON_IDS=${E2E_FOUNDER_PATREON_ID}`,
    `${FOUNDER_PATRON_ID_KEY}=${E2E_FOUNDER_PATREON_ID}`,
    "PATREON_CLIENT_ID=e2e-local-client-id",
    "PATREON_CLIENT_SECRET=e2e-local-client-secret",
    "PATREON_REDIRECT_URI=http://127.0.0.1:3100/api/auth/callback",
  ].join("\n");
}

function ensureDevVars(): void {
  if (existsSync(DEV_VARS_PATH)) {
    const existing = readFileSync(DEV_VARS_PATH, "utf-8");
    // A file from an earlier harness revision is disposable, but only when it is
    // ours: a hand-written .dev.vars stays untouched and the founder fixture simply
    // stays unavailable rather than trusting ids we did not write.
    const isOurs =
      existing.includes(GENERATED_DEV_VARS_MARKER) && !existing.includes(`${FOUNDER_PATRON_ID_KEY}=`);
    if (!isOurs) {
      return;
    }
    writeFileSync(DEV_VARS_PATH, `${localDevVars()}\n`, "utf-8");
    console.log("[e2e] refreshed the generated .dev.vars with the disposable founder key");
    return;
  }
  writeFileSync(DEV_VARS_PATH, `${localDevVars()}\n`, "utf-8");
  console.log("[e2e] wrote a local .dev.vars with throwaway bindings");
}

function ensureEngineMock(): void {
  if (existsSync(ENGINE_MOCK_PATH)) {
    return;
  }
  execFileSync("npx", ["tsx", "scripts/generate-engine-mock.ts"], { cwd: ROOT, stdio: "inherit" });
}

function applyLocalMigrations(): void {
  execFileSync("npx", ["wrangler", "d1", "migrations", "apply", "DB", "--local"], {
    cwd: ROOT,
    stdio: "inherit",
  });
}

async function seedFixtures(): Promise<void> {
  const founderPatronId = readFounderPatronId();
  const seed = buildE2eFixtureSeed(founderPatronId);
  const proxy = await getPlatformProxy();
  const db = proxy.env.DB as D1Database;
  const bucket = proxy.env.GAME_ASSETS as R2Bucket;
  // Shell objects live under the `engine/` prefix; media objects are keyed by their
  // own path, matching what the engine rewrite hands to /api/game.
  const shellFixture = seededShellFixture();

  try {
    for (const session of seed.sessions) {
      await upsertSession(db, session);
    }
    for (const override of seed.overrides) {
      await upsertPatronOverride(db, override);
    }
    if (founderPatronId) {
      // founderPatronId is the dedicated disposable key, never a creator id, so this
      // scoped delete only ever clears the fixture: the suite then proves the
      // env-bootstrap path rather than reading a pre-seeded grant.
      await db
        .prepare("DELETE FROM patron_overrides WHERE patron_id = ?")
        .bind(founderPatronId)
        .run();
    }
    for (const entry of shellFixture) {
      const key = entry.route === "shell" ? `engine/${entry.key}` : entry.key;
      await bucket.put(key, entry.body, {
        httpMetadata: { contentType: entry.contentType },
      });
    }
    console.log(`[e2e] seeded ${seed.sessions.length} session fixture(s)`);
    console.log(`[e2e] seeded ${shellFixture.length} boot-profile fixture object(s)`);
  } finally {
    await proxy.dispose();
  }
}

async function main(): Promise<void> {
  ensureDevVars();
  ensureEngineMock();
  applyLocalMigrations();
  await seedFixtures();
  console.log("[e2e] local environment ready");
}

main().catch((error: unknown) => {
  console.error("[e2e] setup failed:", error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
