import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC_PLUGINS = path.join(ROOT, "src", "engine-plugins");
const MOCK_HTML_PATH = path.join(SRC_PLUGINS, "mock-shell.html");
const BRIDGE_PATH = path.join(SRC_PLUGINS, "Ropoductions_WebBridge.js");
const OUTPUT_PATH = path.join(ROOT, "src", "lib", "engine-mock.generated.ts");

const MOCK_ENGINE_PATHS = ["index.html", "js/plugins/Ropoductions_WebBridge.js"];

function jsStringLiteral(value: string): string {
  // JSON.stringify emits a valid double-quoted JS string literal with all
  // control characters escaped.
  return JSON.stringify(value);
}

function generate(): void {
  const mockHtml = fs.readFileSync(MOCK_HTML_PATH, "utf-8");
  const bridgeSource = fs.readFileSync(BRIDGE_PATH, "utf-8");

  const header = [
    "// AUTO-GENERATED by scripts/generate-engine-mock.ts — DO NOT EDIT.",
    "// Regenerate with `npm run generate:mock` (runs automatically on prebuild).",
    `// Sources: ${path.relative(ROOT, MOCK_HTML_PATH)}, ${path.relative(ROOT, BRIDGE_PATH)}`,
    "",
  ].join("\n");

  const body = [
    `export const MOCK_ENGINE_HTML: string = ${jsStringLiteral(mockHtml)};`,
    "",
    `export const WEB_BRIDGE_SOURCE: string = ${jsStringLiteral(bridgeSource)};`,
    "",
    `export const MOCK_ENGINE_PATHS: string[] = ${JSON.stringify(MOCK_ENGINE_PATHS)};`,
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, header + body, "utf-8");
  console.log(`Generated ${path.relative(ROOT, OUTPUT_PATH)} (${body.length} bytes)`);
}

generate();