import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { signValue } from "../../src/lib/crypto";
import type { CreateSessionInput, UpsertPatronOverrideInput } from "../../src/types/database";

/**
 * E2E fixture identities. Rows are seeded into the local Wrangler D1 state by
 * `scripts/e2e/setup-e2e-env.ts`; specs only read it, so parallel spec files never
 * contend for writes. Cookies minted here are signed with the same secret the dev
 * server reads from `.dev.vars`.
 */
export const E2E_FIXTURES = {
  panelAdmin: { sessionId: "e2e-panel-admin-session", patronId: "e2e-panel-admin" },
  pledgingAdmin: { sessionId: "e2e-pledging-admin-session", patronId: "e2e-pledging-admin" },
  compHolder: { sessionId: "e2e-comp-session", patronId: "e2e-comp-holder" },
  plainPatron: { sessionId: "e2e-plain-patron-session", patronId: "e2e-plain-patron" },
  founder: { sessionId: "e2e-founder-session" },
} as const;

export const E2E_SESSION_COOKIE = "ropoductions_session";
export const E2E_AGE_COOKIE = "ropoductions_age_verified";
export const E2E_ORIGIN = "127.0.0.1";

const DEV_VARS_FILE = ".dev.vars";
const GENERATED_DEV_VARS_MARKER = "# generated-by: scripts/e2e/setup-e2e-env.ts";

function readDevVarsValue(key: string): string | undefined {
  const file = resolve(process.cwd(), DEV_VARS_FILE);
  if (!existsSync(file)) {
    return undefined;
  }

  for (const line of readFileSync(file, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("#") || !trimmed.includes("=")) {
      continue;
    }
    const [name, ...rest] = trimmed.split("=");
    if (name.trim() === key) {
      return rest.join("=").trim().replace(/^["']|["']$/g, "");
    }
  }

  return undefined;
}

/** Secret the running server signs session cookies with, mirroring wrangler's .dev.vars precedence. */
export function readSessionSecret(): string {
  const secret = readDevVarsValue("SESSION_SECRET") ?? process.env.SESSION_SECRET;
  if (!secret) {
    throw new Error(
      "SESSION_SECRET is not configured. Run `npm run e2e:setup` (or set it in .dev.vars) before the e2e suite."
    );
  }
  return secret;
}

/**
 * True when `.dev.vars` was generated by the e2e setup script. Only then are its
 * creator-admin ids disposable fixtures rather than a developer's own identity,
 * which the suite must never overwrite or delete.
 */
export function isGeneratedDevVars(): boolean {
  const file = resolve(process.cwd(), DEV_VARS_FILE);
  return existsSync(file) && readFileSync(file, "utf-8").includes(GENERATED_DEV_VARS_MARKER);
}

/** Founder env-bootstrap identity, available only from the generated local file. */
export function readFounderPatronId(): string | undefined {
  if (!isGeneratedDevVars()) {
    return undefined;
  }
  const raw =
    readDevVarsValue("CREATOR_ADMIN_PATREON_IDS") ?? process.env.CREATOR_ADMIN_PATREON_IDS;
  const first = raw
    ?.split(",")
    .map((value) => value.trim())
    .find((value) => value.length > 0);
  return first ?? undefined;
}

export function daysFromNow(days: number): number {
  return Math.floor(Date.now() / 1000) + days * 24 * 60 * 60;
}

const ADMIN_SEED_GRANTOR = "e2e-seed";

function sessionInput(
  fixture: { sessionId: string; patronId: string },
  overrides: Partial<CreateSessionInput> = {}
): CreateSessionInput {
  return {
    id: fixture.sessionId,
    patron_id: fixture.patronId,
    email: `${fixture.patronId}@ropoductions.test`,
    role: "patron",
    tier_id: "tier-ork",
    tier_name: "Ork Patron",
    pledge_cents: 500,
    encrypted_access_token: "e2e-encrypted-access",
    encrypted_refresh_token: "e2e-encrypted-refresh",
    token_expires_at_sec: daysFromNow(1),
    expires_at_sec: daysFromNow(30),
    // Explicit so a session revoked by an earlier run is restored to a known state.
    revoked: 0,
    ...overrides,
  };
}

export interface E2eFixtureSeed {
  sessions: CreateSessionInput[];
  overrides: UpsertPatronOverrideInput[];
  founderPatronId?: string;
}

/**
 * Fixture rows for the admin chrome specs: one panel-granted admin, one admin who
 * also holds an active pledge (`session.role` stays "patron"), one comp pass, one
 * plain patron, and a founder resolved through env bootstrap with zero override rows.
 */
export function buildE2eFixtureSeed(founderPatronId?: string): E2eFixtureSeed {
  const sessions: CreateSessionInput[] = [
    sessionInput(E2E_FIXTURES.panelAdmin, {
      role: "admin",
      tier_id: "override_admin",
      tier_name: "Studio Admin",
      pledge_cents: 0,
    }),
    sessionInput(E2E_FIXTURES.pledgingAdmin),
    sessionInput(E2E_FIXTURES.compHolder, {
      role: "comp",
      tier_id: "override_comp",
      tier_name: "Complimentary Pass",
      pledge_cents: 0,
    }),
    sessionInput(E2E_FIXTURES.plainPatron),
  ];

  if (founderPatronId) {
    sessions.push(
      sessionInput({ sessionId: E2E_FIXTURES.founder.sessionId, patronId: founderPatronId }, {
        pledge_cents: 0,
      })
    );
  }

  const overrides: UpsertPatronOverrideInput[] = [
    {
      patron_id: E2E_FIXTURES.panelAdmin.patronId,
      role: "admin",
      notes: "E2E panel admin",
      granted_by: ADMIN_SEED_GRANTOR,
    },
    {
      patron_id: E2E_FIXTURES.pledgingAdmin.patronId,
      role: "admin",
      notes: "E2E pledging admin",
      granted_by: ADMIN_SEED_GRANTOR,
    },
    {
      patron_id: E2E_FIXTURES.compHolder.patronId,
      role: "comp",
      notes: "E2E comp pass",
      granted_by: ADMIN_SEED_GRANTOR,
    },
  ];

  return { sessions, overrides, founderPatronId };
}

export async function mintSessionCookie(sessionId: string): Promise<string> {
  return await signValue(sessionId, readSessionSecret());
}

export interface E2eCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
}

/** Session cookies for the local e2e origin, optionally without the age cookie. */
export async function sessionCookies(
  sessionId: string,
  options: { ageVerified?: boolean } = {}
): Promise<E2eCookie[]> {
  const { ageVerified = true } = options;
  const cookies: E2eCookie[] = [
    {
      name: E2E_SESSION_COOKIE,
      value: await mintSessionCookie(sessionId),
      domain: E2E_ORIGIN,
      path: "/",
    },
  ];
  if (ageVerified) {
    cookies.push({ name: E2E_AGE_COOKIE, value: "true", domain: E2E_ORIGIN, path: "/" });
  }
  return cookies;
}
